### ISSUE TITLE
Initialization error with FGFS 2020.4.0

### ISSUE THREAD

**Issue by Attigliuzzo** [SurferTim/dhc6p#4]
Your Twin Otter is great but with FGFS 2020.4.0 isn't usable because i get this:

`
The aircraft flight dynamics model contains errors and cannot be used. (FGGroundCache::get_agl: NaN position input)
`

The floats version is the only usable.
Thanks

**Comment by SurferTim** [comment]
I use both wheel and float on FG2020.4.0 with Ubuntu 18.04. No problems there.
Where are you spawning the aircraft?

**Comment by Attigliuzzo** [comment]
The airport is LIBD. A workaround is disabling the advanced weather in the gui, then enabling it in the menu when sim is loaded.
Same happens with the DC3 from FGaddon.

**Comment by SurferTim** [comment]
I have made a couple mods to FG2020.4.0 to get it working right. Here is the link to the post that fixed the crashes for me. You might want to read the whole thread.
https://forum.flightgear.org/viewtopic.php?f=71&t=39535&hilit=simgear&start=75#p395001

**Comment by Attigliuzzo** [comment]
I'm using the nightly binary Linux and your fix isn't included in the main source code of simgear, so it needs to be recompiled. Anyway i'll read better the whole thread.
Thanks
